"""initial  migration

Revision ID: 55da91f730b1
Revises: 
Create Date: 2024-12-26 13:48:23.550071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55da91f730b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('wind_kph', sa.Float(), nullable=False),
    sa.Column('condition_text', sa.String(length=255), nullable=False),
    sa.Column('condition_icon', sa.String(length=255), nullable=False),
    sa.Column('condition_code', sa.Integer(), nullable=False),
    sa.Column('localtime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name', 'condition_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data')
    # ### end Alembic commands ###
